### ISSUE TITLE
Generated links to posts are incorrect

### ISSUE THREAD

**Issue by jamieburchell** [bolt/bolt-extension-rssfeed#20]
Given this (shortened) `contenttypes.yml` config:

```
blog:
    name: Blog
    singular_name: Post
    slug: blog
    singular_slug: post
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: [title]
            group: content
    taxonomy: [ tags ]
    record_template: blog_entry.twig
    listing_template: listing_blogs.twig
```

And this `rssfeed.bolt.yml` config:

```
sitewide:
    enabled: true
    feed_records: 50
    feed_template: rss.twig
    atom_template: atom.twig
    content_length: 100
    content_types: [ blog ]
```

`<link>` in the resulting RSS feed is incorrect:

`<link>https://www.example.com/blog/example-slug</link>`

It should be:

`<link>https://www.example.com/post/example-slug</link>`

Is there a particular reason why the output in the RSS twig files cannot be changed to use `record.link` for example `<link>{{ absolute_url(record.link) }}</link>` ?

Bolt version 3.2.13 / bolt/rssfeed version 3.2.0
